symbol: EURUSD

data:
  years: 5
  data_dir: /data
  bars_5m: EURUSD_5m.parquet
  bars_1h: EURUSD_1h.parquet

  # ВАЖНО: на Railway выключаем скачивание полностью
  disable_download: true

provider:
  name: twelvedata
  api_key_env: TWELVEDATA_API_KEY

broker:
  leverage: 200
  spread_points: 8
  tick: 0.00001
  margin_call_level: 0.20
  stop_out_level: 0.00

strategy:
  tf_entry: 5m
  tf_range: 1h
  # тут неважно, потому что run_grid на Railway вообще не должен запускаться

report:
  out_dir: /data/out
  save_trades: false
